import { StyleSheet } from 'react-native';

export default function createAppStyles(colors) {
  return StyleSheet.create({
  splashContainer: {
    flex: 1,
    backgroundColor: colors.background,
    overflow: 'hidden',
  },
  glowTopLeft: {
    position: 'absolute',
    top: -80,
    left: -90,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(24, 166, 160, 0.06)',
  },
  glowBottomRight: {
    position: 'absolute',
    right: -90,
    bottom: -90,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(24, 166, 160, 0.05)',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingTop: 96,
    paddingBottom: 42,
  },
  heroBlock: {
    alignItems: 'center',
    width: '100%',
  },
  logoCard: {
    width: 160,
    height: 160,
    borderRadius: 40,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: colors.cardShadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
    overflow: 'hidden',
  },
  logoPulse: {
    position: 'absolute',
    width: 126,
    height: 126,
    borderRadius: 63,
    backgroundColor: 'rgba(24, 166, 160, 0.06)',
  },
  logo: {
    width: 126,
    height: 126,
  },
  brand: {
    fontSize: 46,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -1.2,
  },
  taglineWrap: {
    marginTop: 6,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  taglineWordsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  taglineWord: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 2.2,
    color: colors.mutedText,
  },
  taglineAccent: {
    position: 'absolute',
    top: 8,
    left: 0,
    width: 104,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(24, 166, 160, 0.14)',
  },
  dividerTrack: {
    width: 64,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.accentSoft,
    marginTop: 14,
    marginBottom: 18,
  },
  description: {
    fontSize: 21,
    lineHeight: 31,
    textAlign: 'center',
    color: colors.textSecondary,
    marginBottom: 0,
    maxWidth: 320,
  },
  descriptionDelayed: {
    marginTop: 12,
  },
  descriptionLater: {
    marginTop: 10,
  },
  tapToEnter: {
    marginTop: 18,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: colors.accent,
  },
  });
}